### ISSUE TITLE
Open newly created Teamwork Project is not working

### ISSUE THREAD

**Issue by aryoxp** [DaftPoint/StarUML.Teamwork#3]
Hi, 
I am going to try your StarUML extension on StarUML 2.6.0 for MacOSX. However I can not open my newly created Teamwork Project in order to have it sync'ed with my git repository. The Teamwork|Open Teamwork-Project menu does nothing on my Mac, not even showing any pop up window nor notification.
Any ideas?

**Comment by InteNs** [comment]
same issue for me

**Comment by DaftPoint** [comment]
I don't use Mac so sadly I have no idea what the cause might be. I have to look into this.

**Comment by aryoxp** [comment]
Unfortunately, the issue is also occurred on StarUML 2.6.0 for Windows.

**Comment by linchuanwang** [comment]
+1

**Comment by linchuanwang** [comment]
+1

**Comment by sstadelman** [comment]
+1

**Comment by sstadelman** [comment]
I have debugged a bit on the Mac, and found the following:

The first issue I was facing, was that in the Teamwork configurations, I included the fully-qualified URL of the git repository:  `https://github.my.organization.corp/me/staruml-doc.git`.  This resulted in the `https` protocol being duplicated in the url being used for communicating with the server.  The resolution was to remove `https://` from the repository URL in the Teamwork configuration wizard:  `github.my.organization.corp/me/staruml-doc.git`.  

Once this is completed, then the communication to the git host seems to be ok, and instead of seeing *nothing* when selecting the **Open Teamwork-Project** menu item, I see the following dialog:
![screen shot 2016-04-21 at 11 01 29 am](https://cloud.githubusercontent.com/assets/377404/14719370/b126fa6a-07b0-11e6-8cbd-2015fb98f7b2.png)

Unfortunately, even though I have created 3 Teamwork-Projects, none of them are appearing in this selection widget.  I am debugging now.

**Comment by sstadelman** [comment]
This is a very strange behavior, but I can see that when I select **Open Teamwork-Project** menu item, a new directory is created, named **/Project**, in the **Local Working Directory**.

**Comment by DaftPoint** [comment]
I was able to look into this and could find one Problem. But unfortunately after fixing it i found another bug which appears to show itself after updating to 2.6.0

**Comment by DaftPoint** [comment]
I changed a little functionality so that projects should open and locks should work. A new release should be available in 2 days in the extension registry
